using System.Collections.Generic;
using Content.Client.Administration.Eui;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Log;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminShuttleWindow : DefaultWindow
    {
        private readonly AdminShuttleEui _eui;
        public AdminShuttleWindow(AdminShuttleEui eui)
        {
            RobustXamlLoader.Load(this);
            _eui = eui;
            RefreshButton.OnPressed += _ => _eui.RequestRefresh();
        }

        public void Populate(List<StationInfo> stations)
        {
            StationContainer.RemoveAllChildren();
            foreach (var station in stations)
            {
                var control = new StationEvacControl(station);
                StationContainer.AddChild(control);
            }
        }
    }
}
