using System;
using Content.Shared.Administration;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class StationEvacControl : BoxContainer
    {
        private readonly NetEntity _stationId;

        public StationEvacControl(StationInfo station)
        {
            RobustXamlLoader.Load(this);
            _stationId = station.StationId;

            StationName.Text = station.Name ?? $"Unknown Station ({station.StationId})";
            ShuttleTime.OnTextChanged += OnTimeChanged;
            RecallButton.Command = $"recallevac {_stationId}";

            // Set initial state
            OnTimeChanged(new LineEdit.LineEditEventArgs(ShuttleTime, ShuttleTime.Text));
        }

        private void OnTimeChanged(LineEdit.LineEditEventArgs obj)
        {
            var timeValid = int.TryParse(obj.Text, out var seconds) && seconds >= 0;

            CallButton.Disabled = !timeValid;
            if (timeValid)
            {
                CallButton.Command = $"callevac {seconds} {_stationId}";
            }
        }
    }
}
