using System.Linq;
using Content.Shared.Fax;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client.Fax.UI;

[GenerateTypedNameReferences]
public sealed partial class FaxWindow : DefaultWindow
{
    public event Action? FileButtonPressed;
    public event Action? PaperButtonPressed;
    public event Action? CopyButtonPressed;
    public event Action? SendButtonPressed;
    public event Action? RefreshButtonPressed;
    public event Action<string>? PeerSelected;

    public bool OfficePaper = false;

    public FaxWindow()
    {
        RobustXamlLoader.Load(this);

        PaperButtonPressed += OnPaperButtonPressed;

        FileButton.OnPressed += _ => FileButtonPressed?.Invoke(); 
        PaperButton.OnPressed += _ => PaperButtonPressed?.Invoke(); 
        CopyButton.OnPressed += _ => CopyButtonPressed?.Invoke();
        SendButton.OnPressed += _ => SendButtonPressed?.Invoke();
        RefreshButton.OnPressed += _ => RefreshButtonPressed?.Invoke();
        PeerSelector.OnItemSelected += args =>
            PeerSelected?.Invoke((string) args.Button.GetItemMetadata(args.Id)!);
    }

    public void UpdateState(FaxUiState state)
    {
        CopyButton.Disabled = !state.CanCopy;
        SendButton.Disabled = !state.CanSend;
        FromLabel.Text = state.DeviceName;

        if (state.IsPaperInserted)
        {
            PaperStatusLabel.FontColorOverride = Color.Green;
            PaperStatusLabel.Text = Loc.GetString("fax-machine-ui-paper-inserted");
        }
        else
        {
            PaperStatusLabel.FontColorOverride = Color.Red;
            PaperStatusLabel.Text = Loc.GetString("fax-machine-ui-paper-not-inserted");
        }

        var allPeers = state.StationGroups.SelectMany(g => g.Peers).ToList();

        if (allPeers.Count == 0)
        {
            PeerSelector.Clear();
            PeerSelector.AddItem(Loc.GetString("fax-machine-ui-no-peers"));
            PeerSelector.Disabled = true;
            return;
        }

        PeerSelector.Disabled = false;
        PeerSelector.Clear();

        var selectedId = -1;

        foreach (var group in state.StationGroups)
        {
            // Add a non-selectable header for the station
            PeerSelector.AddItem(group.StationName);
            PeerSelector.SetItemDisabled(PeerSelector.ItemCount - 1, true);

            foreach (var (address, faxInfo) in group.Peers)
            {
                var id = AddPeerSelect(faxInfo.Name, address);
                if (address == state.DestinationAddress)
                    selectedId = id;
            }
        }

        if (selectedId != -1)
        {
            PeerSelector.Select(selectedId);
        }
        // If no destination is selected, select the first available peer
        else if (allPeers.Count > 0)
        {
            PeerSelected?.Invoke(allPeers.First().Key);
        }
    }

    private int AddPeerSelect(string name, string address)
    {
        PeerSelector.AddItem(name);
        PeerSelector.SetItemMetadata(PeerSelector.ItemCount - 1, address);
        return PeerSelector.ItemCount - 1;
    }

    private void OnPaperButtonPressed()
    {
        OfficePaper = !OfficePaper;

        if(OfficePaper)
            PaperButton.Text = Loc.GetString("fax-machine-ui-paper-button-office");
        else
            PaperButton.Text = Loc.GetString("fax-machine-ui-paper-button-normal");
    }
}
